#This playbook can be used to create Network Object Groups from individual entries or lists.
#Object groups can be removed or individual entries removed as well.  All tasks are idempotent.
---
-  name: ASA acl creation
   hosts: asa
   connection: local
   gather_facts: True

   tasks:
     - include_vars: "{{playbook_dir}}/../../passwords.yml"
       #when: ansible_user_id != "jenkins" and decrypt_vault == True
       no_log: True

     - name: Create New Net Object Group
       cisco_asa_network_objectgroup_members:
           host: "{{ inventory_hostname }}"
           username: "{{username}}"
           password: "{{password}}"
           name: kev
           state: present
           #description:
           value: '172.16.32.56'  #if no mask, /32 is assumed
           validate_certs: False

     - name: Create New Net Object Group
       cisco_asa_network_objectgroup_members:
           host: "{{ inventory_hostname }}"
           username: "{{username}}"
           password: "{{password}}"
           name: kev
           state: present
           #description:
           members: 
              - 192.168.124.172/31
              - 192.168.193.231/32
           validate_certs: False

     - name: Add Entry to Net Object Group
       cisco_asa_network_objectgroup_members:
           host: "{{ inventory_hostname }}"
           username: "{{username}}"
           password: "{{password}}"
           name: kev
           state: present
           #description:
           members: 
              - 10.10.10.10/31
           validate_certs: False

     - name: Remove Entry from Net Object Group
       cisco_asa_network_objectgroup_members:
           host: "{{ inventory_hostname }}"
           username: "{{username}}"
           password: "{{password}}"
           name: kev
           state: present
           entry_state: absent
           #description:
           value: '172.16.32.56'
           validate_certs: False           

     - name: Remove list of Entries from Net Object Group
       cisco_asa_network_objectgroup_members:
           host: "{{ inventory_hostname }}"
           username: "{{username}}"
           password: "{{password}}"
           name: kev
           state: present
           entry_state: absent
           #description:
           members: 
              - 192.168.124.172/31
              - 10.10.10.10/31
           validate_certs: False     

     - name: Remove Net Object Group
       cisco_asa_network_objectgroup_members:
           host: "{{ inventory_hostname }}"
           username: "{{username}}"
           password: "{{password}}"
           name: kev
           state: absent
           #entry_state: present #entry state is ignored and may be present, absent or not included when 'state' is absent.
           #description:
           members: [] #Members has no impact on results, but requires an iterable type, here an empty list is used
           validate_certs: False     
